# Generated by Django 6.0.5 on 2026-05-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('doors', models.IntegerField(default=4)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('helmet_included', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Motorcycle',
                'verbose_name_plural': 'Motorcycles',
            },
        ),
    ]
